### ISSUE TITLE
flexible spatial kernel

### ISSUE THREAD

**Issue by annecori** [thibautjombart/quicksim#1]
Could the spatial kernel be specified by a function rather than fixed to be normal? 
For my specific purpose, I want to use a Rayleigh kernel; FYI the code I was using in my old simOutbreak function (adapted from the outbreaker one) to go from your 'reach' parameter to my rayleigh kernel was as follows:

`rayleigh_scale <- reach / sqrt(acos(-1)/2)  # using acos(-1) instead of pi `
`      rayleigh_sd <- sqrt( rayleigh_scale^2*(4-acos(-1))/2 )  # using acos(-1) instead of pi `

[...]

`k.spa <- kernel.rayleigh(res$xy, sd = rayleigh_sd)`

where

`kernel.rayleigh <- function (xy, sd) `
`{`
  `D <- as.matrix(dist(xy))`
  `out <- VGAM::drayleigh(D, scale = sd)`
  `dim(out) <- c(nrow(D), ncol(D))`
  `dimnames(out) <- list(1:nrow(D), 1:ncol(D))`
  `diag(out) <- 0`
  `return(out)`
`}`

**Comment by thibautjombart** [comment]
Done as of 3bbb93cd5155687e3ab4ed9445e0aa8df0a75900

There's a new example in the README:
https://github.com/thibautjombart/quicksim

And also in `?new_location`.  Lemme know if that's okay or if you need anything else on this. If all good, feel free to close the issue :)

**Comment by annecori** [comment]
so - I was actually dumb as when using a normal kernel the distance between cases follows a Rayleigh distribution and that's what I wanted... so shouldn't have bothered you with this - but makes it more flexible which is good I guess! Thanks for sorting out so quickly.
